name: Deploy to Heroku

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Sanitize the Heroku API key in case the UI copy adds spaces/newlines
      - name: Sanitize Heroku API key
        shell: bash
        run: |
          CLEAN=$(printf "%s" "${{ secrets.HEROKU_API_KEY }}" | tr -d '\\r\\n[:space:]')
          echo "HEROKU_API_KEY_CLEAN=$CLEAN" >> "$GITHUB_ENV"

      - name: Deploy via git push (no CLI action)
        shell: bash
        env:
          APP: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          set -euo pipefail
          echo "Key length:" $(printf "%s" "$HEROKU_API_KEY_CLEAN" | wc -c)
          git remote add heroku "https://heroku:${HEROKU_API_KEY_CLEAN}@git.heroku.com/${APP}.git" || git remote set-url heroku "https://heroku:${HEROKU_API_KEY_CLEAN}@git.heroku.com/${APP}.git"
          git push heroku HEAD:main -f
